#
# Function to generate crude mortality and z-score graphs
# Input: dataframe generated by baseline function
#

output.graph <- function(data) {
  # **This part should be deleted in the final version
  # Temporal assignment of data, first run testing-base.R
  data <- final
  # Add additional information (to be added: should be part of data already)
  data <- within(data, {
    Version <- "v4-3"
    Model <- "LINE"
    source <- "HPA"
    country <- "England"
    group <- "Total"
    DateoA <- euromomoCntrl$dAggregation
    WoAi <- as.numeric(substr(ISOweek::date2ISOweek(DateoA), start = 7, stop = 8))
    YoAi <- as.numeric(substr(ISOweek::date2ISOweek(DateoA), start = 1, stop = 4))
  })
  # **to here

  #
  # Graph: crude mortality
  #

  # Open connection to png file
  filename <- paste0("Graph-Number_of_deaths-", data$group[1], ".png")
  png(filename = file.path(week.dir, filename), width = 1920, height = 1080, units = "px", pointsize = 20)

  # Create layout: one for the graph, one for the legend
  layout(mat = matrix(c(1, 2), nrow = 2, ncol = 1), heights = c(4, 1))
  # Graph
  par(mar = c(1.5, 2.5, 3, 2.5))
  plot.new()
  with(data, {
    plot.window(xlim = c(1, nrow(data)), ylim = range(cnb))
    idx <- which(WoDi == WoDi[nrow(data)])
    axis(side = 1, at = idx, labels = ISOweek[idx])
    axis(side = 2)
    box()
    title(main = paste("Number of deaths -", ISOweek[nrow(data)], "\n", country[1], "- Group", group[1]))
    # Add the graphs
    lines(x = 1:nrow(data), y = onb, col = "black")
    lines(x = 1:nrow(data), y = ifelse(CondDelays == 0, cnb, NA), col = "green")
    lines(x = 1:nrow(data), y = ifelse(CondSeason == 1, onb, NA), col = "blue")
    lines(x = 1:nrow(data), y = pnb, col = "red")
    # Only plot prediction intervals that are smaller than max(onb)
    for (multiplier in seq(from = 2, to = 20, by = 2)) {
      z <- (pnb^(2/3)+ multiplier*pv.pnb)^(3/2)
      if (all(z < max(onb))) lines(x = 1:nrow(data), y = z, col = "yellow")
    }
  })
  # Legend
  par(mar = rep(0, 4))
  plot.new()
  plot.window(xlim = c(0, 1), ylim = c(0, 1))
  legend(
    x = "center",
    xjust = 0.5, yjust = 0.5,
    legend = c("Known number of deaths", "Data used in model", "Corrected number deaths",
      "Baseline", "Prediction interval by 2 stdv"),
    lty = 1,
    col = c("black", "blue", "green", "red", "yellow"),
    ncol = 2
  )

  # Close connection to png file
  dev.off()

  #
  # Graph: z-scores
  #

  # Open connection to png file
  filename <- paste0("Graph-Zscore-", data$group[1], ".png")
  png(filename = file.path(week.dir, filename), width = 1920, height = 1080, units = "px", pointsize = 20)

  # Create layout: one for the graph, one for the legend
  layout(mat = matrix(c(1, 2), nrow = 2, ncol = 1), heights = c(4, 1))
  # Graph
  par(mar = c(1.5, 2.5, 3, 2.5))
  plot.new()
  with(data, {
    plot.window(xlim = c(1, nrow(data)), ylim = range(Zscore))
    idx <- which(WoDi == WoDi[nrow(data)])
    axis(side = 1, at = idx, labels = ISOweek[idx])
    axis(side = 2, at = seq(from = -20, to = 20, by = 2))
    abline(h =  seq(from = -20, to = 20, by = 2), col = "yellow")
    abline(h = 0, col = "red")
    box()
    title(main = paste("Z-score -", ISOweek[nrow(data)], "\n", country[1], "- Group", group[1]))
        # Add the graphs
    lines(x = 1:nrow(data), y = Zscore, col = "black")
    lines(x = 1:nrow(data), y = ifelse(CondSeason == 1, Zscore, NA), col = "blue")
  })
  # Legend
  par(mar = rep(0, 4))
  plot.new()
  plot.window(xlim = c(0, 1), ylim = c(0, 1))
  legend(
    x = "center",
    xjust = 0.5, yjust = 0.5,
    legend = c("Z-score", "Data used in model", "Baseline", "Standard deviations by 2"),
    lty = 1,
    col = c("black", "blue", "red", "yellow"),
    ncol = 2
  )

  # Close connection to png file
  dev.off()
}

#
# Function to generate cumulated mortality tables
# Input: dataframe generated by baseline function
# Ouput: textfile with the cumulated mortality table
#

output.table <- function(data) {
  # **This part should be deleted in the final version
  # Temporal assignment of data, first run testing-base.R
  data <- final
  # Add additional information (to be added: should be part of data already)
  data <- within(data, {
    Version <- "v4-3"
    Model <- "LINE"
    source <- "HPA"
    country <- "England"
    group <- "Total"
    DateoA <- euromomoCntrl$dAggregation
    WoAi <- as.numeric(substr(ISOweek::date2ISOweek(DateoA), start = 7, stop = 8))
    YoAi <- as.numeric(substr(ISOweek::date2ISOweek(DateoA), start = 1, stop = 4))
  })
  # **to here

  # Define variable that defines winter and summer season
  data <- within(data, season <- ifelse(WoDi >= 40 | WoDi <= 20, paste0("Winter-", YoDi-(WoDi <= 20)), paste0("Summer-", YoDi)))

  # Split data according to season -> generates a list of dataframes
  data.split <- with(data, split(data, f = season))

  # Apply cumulative moratality function to each dataframe in the list data.split
  tmp <- lapply(data.split, function(x) {
    with(x, data.frame(
      Start = ISOweek[1],
      End = ISOweek[nrow(x)],
      Nweeks = nrow(x),
      CumDeaths = round(sum(cnb), digits = 2),
      CumExcess = round(sum(excess), digits = 2)))
  })

  # And apppend them togeter into one dataframe
  cummort.data <- do.call(what = "rbind", args = tmp)

  # Save cummort.data in a text file
  filename <- paste0("Cumulative_mortality_", data$group[1], ".txt")
  capture.output(print(cummort.data), file = file.path(week.dir, filename))
}
